zuul:
  routes:
    my-service:
      path: /my-service/**
      serviceId: my-service
    get:
      path: /get/**
      url: http://httpbin.org/get
    links:
      path: /links/**
      url: http://httpbin.org/links
    images:
      path: /image/**
      url: http://httpbin.org/image

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/